permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "blog.sublime-project", "blog.sublime-workspace"]
pygments: true

title : GSoC '14 Progress Blog
tagline: Porting Flumotion to gstreamer-1.x API - under TimVideos.us
author :
  name : Amanpreet Singh
  email : aps.sids@gmail.com
  github : aps-sids
  facebook: amanz008
  twitter : aps_sids
  linkedin : amanpreet-singh/26/802/666
  google_plus : 114056544272791132056

comments :
  provider : disqus
  disqus :
    short_name : aps-sids