permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "blog.sublime-project", "blog.sublime-workspace"]
pygments: true
markdown: kramdown
kramdown:
  use_coderay: false

url : http://apsops.github.io/porting-flumotion
title : GSoC '14 Progress Blog
tagline: Porting Flumotion to gstreamer-1.x API - under TimVideos.us
author :
  name : Amanpreet Singh
  email : aps.sids@gmail.com
  github : ApsOps
  facebook: amanz008
  twitter : ApsOps
  linkedin : amanpreet-singh/26/802/666
  google_plus : "114056544272791132056"

comments :
  provider : disqus
  disqus :
    short_name : aps-sids
